language: node_js
node_js:
  - '10'
  - node
install:
- yarn
script:
- yarn test
- yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  bucket: 'devopstravis.com'
  local_dir: dist
  skip_cleanup: true
  on:
    branch: master


