language: node_js
node_js:
  - '10'
  - node
install:
- npm install
script:
- CI=false npm run build
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  region: us-east-1
  app: "node-js-app-bs1"
  env: "NodeJsAppBs1-env"
  bucket_name: "elasticbeanstalk-us-east-1-736998360651"
  skip_cleanup: true
  on:
    branch: s3-elasticbeanstalk-node


