language: node_js
node_js:
  - '10'
  - node
install:
- npm install
script:
- CI=false npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  bucket: 'devtravis.com'
  local_dir: build
  region: us-west-2
  skip_cleanup: true
  on:
    branch: master


